// Generated by tauri-specta (`cargo test` in src-tauri). Do not edit by hand.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	docOpen: (source: OpenSource) => __TAURI_INVOKE<OpenResult>("doc_open", { source }),
	docClose: (handle: DocHandle) => __TAURI_INVOKE<boolean>("doc_close", { handle }),
	docGetSlice: (handle: DocHandle, path: Path, start: number, end: number) => __TAURI_INVOKE<NodeView[]>("doc_get_slice", { handle, path, start, end }),
	docGetValue: (handle: DocHandle, path: Path) => __TAURI_INVOKE<string & { readonly __brand: "LosslessText" }>("doc_get_value", { handle, path }),
	docGetRows: (handle: DocHandle, path: Path, start: number, end: number) => __TAURI_INVOKE<(string & { readonly __brand: "LosslessText" })[]>("doc_get_rows", { handle, path, start, end }),
	docGetRowsSorted: (handle: DocHandle, path: Path, start: number, end: number, key: string, descending: boolean) => __TAURI_INVOKE<RowJson[]>("doc_get_rows_sorted", { handle, path, start, end, key, descending }),
	docGetRowsFiltered: (handle: DocHandle, path: Path, start: number, end: number, query: GridQuery, jobId: string | null) => __TAURI_INVOKE<FilteredRowsJson>("doc_get_rows_filtered", { handle, path, start, end, query, jobId }),
	docColumnValues: (handle: DocHandle, path: Path, key: string, limit: number) => __TAURI_INVOKE<ColumnValues>("doc_column_values", { handle, path, key, limit }),
	docGetRowsAt: (handle: DocHandle, path: Path, indices: number[]) => __TAURI_INVOKE<string & { readonly __brand: "LosslessText" }>("doc_get_rows_at", { handle, path, indices }),
	docSummary: (handle: DocHandle) => __TAURI_INVOKE<Summary>("doc_summary", { handle }),
	docChildCount: (handle: DocHandle, path: Path) => __TAURI_INVOKE<number | null>("doc_child_count", { handle, path }),
	docColumnSchema: (handle: DocHandle, path: Path) => __TAURI_INVOKE<ColumnSchema>("doc_column_schema", { handle, path }),
	docApplyOp: (handle: DocHandle, op: Op) => __TAURI_INVOKE<ApplyResult>("doc_apply_op", { handle, op }),
	docSetRootText: (handle: DocHandle, text: string) => __TAURI_INVOKE<ApplyResult>("doc_set_root_text", { handle, text }),
	docUndo: (handle: DocHandle) => __TAURI_INVOKE<{
	version: number,
	affectedPaths: Path[],
} | null>("doc_undo", { handle }),
	docRedo: (handle: DocHandle) => __TAURI_INVOKE<{
	version: number,
	affectedPaths: Path[],
} | null>("doc_redo", { handle }),
	docDiff: (left: DocHandle, right: DocHandle, jobId: string | null) => __TAURI_INVOKE<DiffEntry[]>("doc_diff", { left, right, jobId }),
	docDiffLines: (left: DocHandle, right: DocHandle, jobId: string | null) => __TAURI_INVOKE<LineDiffResult>("doc_diff_lines", { left, right, jobId }),
	docGetLines: (handle: DocHandle, start: number, end: number) => __TAURI_INVOKE<string[]>("doc_get_lines", { handle, start, end }),
	docCanonicalText: (handle: DocHandle) => __TAURI_INVOKE<string & { readonly __brand: "LosslessText" }>("doc_canonical_text", { handle }),
	docCanonicalOffsets: (handle: DocHandle, paths: Path[]) => __TAURI_INVOKE<(CanonicalRange | null)[]>("doc_canonical_offsets", { handle, paths }),
	docSearch: (handle: DocHandle, opts: SearchOptions, jobId: string | null) => __TAURI_INVOKE<SearchHit[]>("doc_search", { handle, opts, jobId }),
	cancelJob: (jobId: string) => __TAURI_INVOKE<boolean>("cancel_job", { jobId }),
	docReplace: (handle: DocHandle, query: string, replacement: string, caseSensitive: boolean) => __TAURI_INVOKE<ReplaceResult>("doc_replace", { handle, query, replacement, caseSensitive }),
	docRepairText: (text: string) => __TAURI_INVOKE<RepairResult>("doc_repair_text", { text }),
	docValidateSchema: (handle: DocHandle, schema: string) => __TAURI_INVOKE<SchemaValidationResult>("doc_validate_schema", { handle, schema }),
	docGenerateTypes: (handle: DocHandle, lang: TypegenLang, typeName: string) => __TAURI_INVOKE<string>("doc_generate_types", { handle, lang, typeName }),
	docDetectAndConvert: (text: string) => __TAURI_INVOKE<DetectResult>("doc_detect_and_convert", { text }),
	docDiagnose: (text: string) => __TAURI_INVOKE<Diagnosis>("doc_diagnose", { text }),
	docHistory: (handle: DocHandle) => __TAURI_INVOKE<HistoryView>("doc_history", { handle }),
	docSave: (handle: DocHandle, path: string | null) => __TAURI_INVOKE<SaveResult>("doc_save", { handle, path }),
	docSetFilePath: (handle: DocHandle, path: string) => __TAURI_INVOKE<Summary>("doc_set_file_path", { handle, path }),
	docBackup: (handle: DocHandle, displayName: string | null) => __TAURI_INVOKE<boolean>("doc_backup", { handle, displayName }),
	docBackupClear: (docId: string) => __TAURI_INVOKE<null>("doc_backup_clear", { docId }),
	docBackupScan: () => __TAURI_INVOKE<BackupRecord[]>("doc_backup_scan"),
	docExport: (handle: DocHandle, format: ExportFormat) => __TAURI_INVOKE<string>("doc_export", { handle, format }),
	docExportPreview: (handle: DocHandle, format: ExportFormat, maxChars: number) => __TAURI_INVOKE<ExportPreview>("doc_export_preview", { handle, format, maxChars }),
	docExportToFile: (handle: DocHandle, format: ExportFormat, path: string) => __TAURI_INVOKE<null>("doc_export_to_file", { handle, format, path }),
	refreshRecentFiles: (items: RecentFile[]) => __TAURI_INVOKE<null>("refresh_recent_files", { items }),
	drainPendingFiles: () => __TAURI_INVOKE<string[]>("drain_pending_files"),
};

/* Constants */
export const EDIT_SIZE_LIMIT = 209715200 as const;

export const LINE_FETCH_MAX = 5000 as const;

export const MAX_DOC_BYTES = 2147483648 as const;

/* Types */
export type ApplyResult = {
	version: number,
	affectedPaths: Path[],
};

export type BackupRecord = {
	docId: string,
	originalPath: string | null,
	displayName: string | null,
	updatedAt: string,
	content: string,
};

export type CanonicalRange = {
	start: number,
	end: number,
};

export type Column = {
	key: string,
	kinds: NodeKind[],
	dominantKind: NodeKind,
	presence: number | null,
	nullable: boolean,
};

export type ColumnSchema = {
	gridSuitable: boolean,
	reason: GridUnsuitableReason | null,
	rowCount: number,
	sampled: number,
	columns: Column[],
};

export type ColumnValue = {
	value: string & { readonly __brand: "LosslessText" },
	count: number,
};

export type ColumnValues = {
	values: ColumnValue[],
	capped: boolean,
};

export type DetectKind = "json" | "yaml" | "xml" | "csv" | "curl" | "unknown";

export type DetectResult = {
	kind: DetectKind,
	json: string,
	error: string | null,
};

export type Diagnosis = {
	title: string,
	detail: string,
	excerpt: DiagnosisExcerpt | null,
	fix: DiagnosisFix | null,
};

export type DiagnosisExcerpt = {
	text: string,
	caret: number,
	line: number,
	column: number,
	clippedStart: boolean,
	clippedEnd: boolean,
};

export type DiagnosisFix = {
	label: string,
	text: string,
	warnings: string[],
};

export type DiffEntry = {
	path: Path,
	kind: DiffKind,
	leftPreview: string | null,
	rightPreview: string | null,
	fromIndex: number | null,
};

export type DiffKind = "added" | "removed" | "changed" | "moved";

export type DocHandle = string;

export type ErrorKind = "notFound" | "invalidPath" | "tooLarge" | "rangeTooLarge" | "parse" | "edit" | "schema" | "export" | "io" | "cancelled";

export type ExportFormat = "json" | "json-min" | "yaml" | "csv" | "xml";

export type ExportPreview = {
	text: string,
	truncated: boolean,
};

export type FilterOp = "contains" | "notContains" | "eq" | "ne" | "gt" | "gte" | "lt" | "lte" | "isEmpty" | "isNotEmpty" | "in" | "notIn" | "startsWith";

export type FilteredRowsJson = {
	total: number,
	rows: RowJson[],
};

export type GridFilter = {
	key: string,
	op: FilterOp,
	value?: string & { readonly __brand: "LosslessText" } | null,
};

export type GridQuery = {
	groups: GridFilter[][],
	quick: string | null,
	quickKeys: string[],
	sortKey: string | null,
	descending: boolean,
};

export type GridUnsuitableReason = "not-array" | "empty" | "non-object-elements" | "too-divergent";

export type HistoryView = {
	undo: OpDescription[],
	redo: OpDescription[],
	cap: number,
};

export type LineDiffResult = {
	hunks: LineHunk[],
	leftLines: number,
	rightLines: number,
};

export type LineHunk = {
	leftStart: number,
	leftLen: number,
	rightStart: number,
	rightLen: number,
};

export type MatchField = "key" | "value";

export type NodeKind = "object" | "array" | "string" | "number" | "bool" | "null";

export type NodeView = {
	key: PathSegment,
	kind: NodeKind,
	preview: string,
	childCount: number | null,
};

export type Op = { kind: "setValueText"; path: Path; text: string } | { kind: "renameKey"; path: Path; from: string; to: string } | { kind: "deleteKey"; path: Path; key: string } | { kind: "deleteItem"; path: Path; index: number } | { kind: "moveItem"; path: Path; from: number; to: number } | { kind: "reorderKeys"; path: Path; order: string[] } | { kind: "sortKeys"; path: Path; descending: boolean } | { kind: "duplicateItem"; path: Path; index: number } | { kind: "duplicateKey"; path: Path; from: string; to: string; position: number | null } | { kind: "insertItemText"; path: Path; index: number; text: string } | { kind: "insertKeyText"; path: Path; key: string; text: string; position: number | null };

export type OpDescription = {
	label: string,
	pathDisplay: string,
};

export type OpenResult = {
	handle: DocHandle,
	summary: Summary,
};

export type OpenSource = { kind: "file"; path: string } | { kind: "text"; text: string; name: string | null };

export type Path = PathSegment[];

export type PathSegment = string | number;

export type RecentFile = {
	path: string,
	name: string,
};

export type RepairResult = {
	success: boolean,
	repairedJson: string,
	errors: string[],
	warnings: string[],
	originalLength: number,
	repairedLength: number,
	wasUnescaped: boolean,
	cleanedUp: boolean,
};

export type ReplaceResult = {
	count: number,
	applied: ApplyResult | null,
};

export type RowJson = {
	index: number,
	value: string & { readonly __brand: "LosslessText" },
};

export type SaveResult = {
	path: string,
	version: number,
};

export type SchemaError = {
	instancePath: string,
	schemaPath: string,
	message: string,
};

export type SchemaValidationResult = {
	valid: boolean,
	errors: SchemaError[],
	errorCount: number,
	truncated: boolean,
};

export type SearchHit = {
	path: Path,
	kind: NodeKind,
	matchField: MatchField,
	snippet: string,
};

export type SearchOptions = {
	query: string,
	caseSensitive?: boolean,
	maxResults?: number | null,
};

export type Summary = {
	rootKind: NodeKind,
	rootChildCount: number | null,
	sourcePath: string | null,
	sourceSize: number,
	lazy: boolean,
	version: number,
	dirty: boolean,
	fileBacked: boolean,
	recoveryNote: string | null,
	commentsStripped: boolean,
};

export type TypegenLang = "typescript" | "rust" | "go" | "kotlin" | "json-schema" | "python" | "php" | "java" | "zod" | "dart";

export type WireError = {
	kind: ErrorKind,
	message: string,
	detail: string | null,
	path: Path | null,
	actual: number | null,
	limit: number | null,
};

